[package]
name = "crustabri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "crustabri"
path = "src/lib.rs"

[[bin]]
name = "qbf_rs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.65"
cadical = "0.1.13"
crusti_app_helper = {path = "local_crates/crusti_app_helper-v0.1"}
lazy_static = "1.4.0"
regex = "1.6.0"
